name: Build

on: push

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Build package
        run: |
          python helper.py package dev-${GITHUB_SHA}
          mkdir tmp
          unzip kart.zip -d tmp

      - uses: actions/upload-artifact@v4
        with:
          name: kart_package
          path: tmp
